# Site settings
course_name: Deep Learning for Engineers
course_description: "This course provides an introduction to deep learning. We will learn about the basics of deep neural networks, and their applications to different tasks in engineering. Students will be able to apply deep learning to a variety of artificial intelligence tasks pertinent to different engineering problems. Applications of deep learning in Mechanical, chemical, biological, Electrical and material engineering will be discussed."
course_semester: "Spring 2021"

baseurl: "/24789spring21" # the subpath of your site, e.g. /blog/
url: "https://baratilab.github.io/" # the base hostname & protocol for your site

schoolname: "Carnegie Mellon University"
# schoolurl: "https://www.meche.engineering.cmu.edu"
# twitter_username: AmirBaratiF 

address: |
    Department of Mechanical Engineering
    Carnegie Mellon University
    Pittsburgh, PA 15213, USA

    <small>Website maintained by <a href="https://linkedin.com/in/yuyangwang-1995">Yuyang Wang</a>. Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/kazemnejad/jekyll-course-website-template">course-website</a> template. Hosted by <a href="https://pages.github.com/">GitHub Pages</a>.</small></p>

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
